{% set name = "soupy" %}
{% set version = "0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/soupy-{{ version }}.tar.gz
  sha256: a65ab9a2f83827df6e0cb2890c94bac7c847082752ba73c094b11c3213a345eb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - pypandoc <1.8.0
    - python {{ python_min }}
  run:
    - beautifulsoup4
    - python >={{ python_min }}
    - six

test:
  imports:
    - soupy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/ChrisBeaumont/soupy
  doc_url: https://soupy.readthedocs.io/en/stable/
  summary: Easier wrangling of web documents
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
